### ISSUE TITLE
🐛: Check the background image/texture is showing is showing up on every page

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v8-geckos-team-07#50]
**Describe the bug**
Troubleshooting after login and the texture background is not showing up. Background is just white.

**To Reproduce**
Login and background is white.

URL is: `http://localhost:3000/dashboard`

If you try navigating to root after logging in site redirects to same location `http://localhost:3000/dashboard` but background shows up.

**Expected behavior**

Background should be shown on every page regardless of navigation. Dashboard page may need to be better defined, ie functionality placed in header.

**Screenshots**

## After login/manually going to location:

![image](https://user-images.githubusercontent.com/602422/55883215-ec940100-5b73-11e9-9998-0ae2167dd3da.png)

## After login but trying to navigate to root and getting redirect:
![image](https://user-images.githubusercontent.com/602422/55883622-a9865d80-5b74-11e9-9d8c-67aa19433837.png)

**Comment by paulywill** [comment]
Might be related to `<main> </main> ` ?

**Comment by SaraSweetie** [comment]
I believe this is fixed with my recent PR. Moving the css up to index.css instead of App.css may have fixed this. 

The background image is implemented to the <body> tag so it should be applied to every page.

**Comment by paulywill** [comment]
I'm still experiencing loading issues.

If I refresh /dashboard it loads up white background... if I do anything (ie resize the window) it will draw the background
